# Generated by Django 6.1.1 on 2026-09-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='wedding', max_length=32)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('baptism', 'Baptême'), ('corporate', 'Événement pro'), ('other', 'Autre')], default='wedding', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('venue_name', models.CharField(blank=True, default='', max_length=200)),
                ('venue_city', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.invitationtemplate')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('rsvp_status', models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente'), ('maybe', 'Peut-être'), ('declined', 'Refusé')], default='pending', max_length=20)),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('drink', models.CharField(blank=True, max_length=80, null=True)),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('maybe', 'Peut-être')], max_length=10)),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='events.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('seats', models.PositiveIntegerField(default=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='events.event')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='events.table'),
        ),
    ]
