# Generated by Django 6.1.1 on 2026-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='studio_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('studio_key__isnull', False), models.Q(('studio_key', ''), _negated=True)), fields=('event', 'studio_key'), name='uniq_guest_studio_key_per_event'),
        ),
    ]
