# Generated by Django 6.1.1 on 2026-09-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_guest_studio_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='studio_config',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot studio (cover, story, programme, galerie, thème…) servi à l’invité.'),
        ),
    ]
