# Generated by Django 6.1.1 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_studio_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme_key',
            field=models.CharField(blank=True, default='', help_text='Clé de palette choisie à la création (ex. sauge, champagne).', max_length=40),
        ),
    ]
